export default {
  ASYNC_STORAGE: {
    TOKEN: 'TOKEN',
  },
  SCREENS: {
    LOGIN: 'LOGIN',
    HOME: {
      HOME_TAB: 'HOME_TAB',
      HOME: 'HOME',
    },
    QR: 'QR',
    SCAN_QR: 'SCAN_QR',
    WORKOUT_STARTER: 'WORKOUT_STARTER',
    PROFILE: 'PROFILE',
    FORGOT: 'FORGOT',
    SPLASH: 'SPLASH',
    ROUTINE: {
      ROUTINES: 'ROUTINES',
      NEWROUTINE: 'NEW_ROUTINE',
    },
    WORKOUT_FLOW: {
      ROUTINE_SELECTION: 'ROUTINE_SELECTION',
      ROUTINE_MANAGER: 'ROUTINE_MANAGER',
    },
  },
};
